### ISSUE TITLE
Core user friendly names not being generated correctly

### ISSUE THREAD

**Issue by mshadbolt** [HumanCellAtlas/schema-template-generator#14]
The current version of the schema-template-generator is not generating the user friendly names for core fields correctly in the spreadsheet. Non-core fields appear to be generating their user friendly names correctly.

example of what is currently being outputted to the Donor Organism tab
```
DONOR_ORGANISM.BIOMATERIAL_CORE.BIOMATERIAL_ID.USER_FRIENDLY (Required)
DONOR_ORGANISM.BIOMATERIAL_CORE.BIOMATERIAL_NAME.USER_FRIENDLY
DONOR_ORGANISM.BIOMATERIAL_CORE.BIOMATERIAL_DESCRIPTION.USER_FRIENDLY
```

Initially @malloryfreeberg said she can take a quick look at it and if she can't figure it out @simonjupp will take a look at it next week.

**Comment by malloryfreeberg** [comment]
Spent 20 mins looking and couldn't figure it out. If @simonjupp could take a look, that would be great.

**Comment by daniwelter** [comment]
This is an issue with the ingest-client spreadsheet builder, not the generator. Awaiting new release of ingest-client.
