### ISSUE TITLE
Change "Project - Funding source(s)" to "Project - Funders" tab name

### ISSUE THREAD

**Issue by zperova** [HumanCellAtlas/schema-template-generator#16]
Currently, the spreadsheet generator created a spreadsheet with the name Project - Funding source(s) - this name is incorrect and will not be parsed by Ingest. 

The code needs to be corrected to display Project - Funders.

Snapshot of the incorrect tab names in spreadsheet generator and spreadsheet below:

<img width="1318" alt="Screenshot 2019-08-20 at 12 34 34" src="https://user-images.githubusercontent.com/38244059/63343862-ee05df00-c346-11e9-860b-5e9d3529d702.png">

<img width="777" alt="Screenshot 2019-08-20 at 12 36 22" src="https://user-images.githubusercontent.com/38244059/63343986-42a95a00-c347-11e9-9adb-baf7eed2d0f0.png">

**Comment by daniwelter** [comment]
The rule encoded in the template generator is that for dependent tabs (funders, publications, contributors etc), the tab name is "Primary type user friendly name - Field user friendly name". If there is a mismatch between what the tab is called and what it should be called, this suggests that the user friendly name of the funders field in project is wrong. I would suggest fixing this in the metadata schema to keep the fix universal.
Alternatively, the desired tab name will have to be hardcoded in the generator with an override of the standard rule for that particular tab. I would advise against this as it adds an extra burden for cross-checking and legacy knowledge to any future metadata schema updates.

**Comment by zperova** [comment]
Thanks, @daniwelter I could not figure out where it is coming from, because I checked everywhere except for the type schema (of course). Will file the ticket in the metadata repo. Closing this issue.
