### ISSUE TITLE
Feature requests for yaml-to-spreadsheet generator

### ISSUE THREAD

**Issue by malloryfreeberg** [HumanCellAtlas/schema-template-generator#2]
See comments in this [doc](https://docs.google.com/document/d/1YAacnbhNkeCY_sJbBV2wc6wxGZhFhY9Lt1BDXYhz4wY/edit). Briefly:

- Add indication of (Required) to required fields in Contact and Publication tabs (Contact name, institution).
- Replace "Biomaterial ID" with "Donor ID", "Biomaterial Name" with "Donor Name", and "Biomaterial - Description" with "Donor Description".
- Hide all ".ontology" and ".ontology_label" columns.
- Rename all ontologized ".text" fields to use the user-friendly terms (then resized the column).
- Removed "(Required)" from all ontologized ".text" fields that aren't actually required.
- Rename Timecourse fields with user-friendly names.
- Update descriptions for ontologized fields to be from the importing schema, not the ontology schema.
- Add "Collection" to the beginning of Protocol ID, Protocol Name, and Protocol Description
- Add "Cell" and "UMI" to barcode-related fields (Offset, Length, Containing read, White list file)
- Add reagent kit types to beginning of reagent field names (Spike-in kit, Library construction kit, Nucleic acid conversion kit)

**Comment by daniwelter** [comment]
Most of these are done, apart from the scenario-specific renames (eg biomaterial ID > donor ID for donor tab + linking fields, same for protocols, barcodes, kit types).

Which ones of these are still relevant?

**Comment by malloryfreeberg** [comment]
Making a list here, categories into themes.

#### Importing core fields

- [ ] For `biomaterial_core.biomaterial_id` fields, replace "BIOMATERIAL ID" user-friendly name with "{type schema title} ID" where {type schema title} is the `title` of the type schema. E.g. "BIOMATERIAL ID" -> "DONOR ORGANISM ID"
- [ ] For `biomaterial_core.biomaterial_name` fields, replace "BIOMATERIAL NAME" user-friendly name with "{type schema title} NAME" where {type schema title} is the `title` of the type schema. E.g. "BIOMATERIAL NAME" -> "DONOR ORGANISM NAME"
- [ ] For `biomaterial_core.biomaterial_description` fields, replace "BIOMATERIAL DESCRIPTION" user-friendly name with "{type schema title} DESCRIPTION" where {type schema title} is the `title` of the type schema. E.g. "BIOMATERIAL DESCRIPTION" -> "DONOR ORGANISM DESCRIPTION"
- [ ] 
- [ ] 

#### Importing modules

- [ ] For `specimen_from_organism.purchased_specimen.*`, prepend all * fields with user-friendly name for `purchased_specimen`. E.g. for `specimen_from_organism.purchased_specimen.retail_name`, "RETAIL NAME" -> "PURCHASED SPECIMEN RETAIL NAME"
- [ ] Same for 
- [ ] 

#### Linking protocols
- [ ] 

#### Linking input biomaterials

- [ ] For `donor_organism.biomaterial_core.biomaterial_id` field in Specimen tab, replace "BIOMATERIAL ID" user-friendly name with "INPUT {type schema title} ID" where {type schema title} is the `title` of the type schema. E.g. "BIOMATERIAL ID" -> "INPUT DONOR ORGANISM ID"
- [ ] Repeat for all biomaterial linking fields selected in template generator. E.g. in Cell suspension tab, `specimen_from_organism.biomaterial_core.biomaterial_id` user-friendly name changes from "BIOMATERIAL ID" -> "INPUT SPECIMEN FROM ORGANISM ID"

**Comment by daniwelter** [comment]
@malloryfreeberg In order to avoid too much hard-coding and keep the rules as general as possible, the module naming rules are applied to all purchased reagent modules and all barcode imports as long as they aren't arrays. This includes the Probe module. It is worth bearing this in mind if more purchased reagents references are added to any schemas.

**Comment by daniwelter** [comment]
Final set of code changes for this now in master in the spreadsheet generator and ingest-client (as appropriate. Closing this ticket - please file bug reports separately.
